### ISSUE TITLE
[BUG] SyntaxError, Any way to fix this?

### ISSUE THREAD

**Issue by BrightDersonS** [AnthonyMichaelTDM/DRG-Save-Editor#35]
File "./src/main/python/main.py", line 1188
    stats: dict[str, Any] = dict() # type: ignore
    ^
SyntaxError: annotated name 'stats' can't be global

This appears when trying to start the save editor with "python ./src/main/python/main.py"

**Comment by AnthonyMichaelTDM** [comment]
That’s odd, make sure you’re using the right Python version and everything Sent from my iPhoneOn Aug 21, 2023, at 5:07 AM, BrightDersonS ***@***.***> wrote:﻿
File "./src/main/python/main.py", line 1188
stats: dict[str, Any] = dict() # type: ignore
^
SyntaxError: annotated name 'stats' can't be global
This appears when trying to start the save editor with "python ./src/main/python/main.py"

**Comment by BrightDersonS** [comment]
> That’s odd, make sure you’re using the right Python version and everything Sent from my iPhoneOn Aug 21, 2023, at 5:07 AM, BrightDersonS ***@***.***> wrote:﻿ File "./src/main/python/main.py", line 1188 stats: dict[str, Any] = dict() # type: ignore ^ SyntaxError: annotated name 'stats' can't be global This appears when trying to start the save editor with "python ./src/main/python/main.py" —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

Yep, Silly me, I downloaded 3.10 but forgot to uninstall 3,7. It works now

**Comment by AnthonyMichaelTDM** [comment]
Good to know, glad we got this resolved Sent from my iPhoneOn Aug 21, 2023, at 10:21 AM, BrightDersonS ***@***.***> wrote:﻿

That’s odd, make sure you’re using the right Python version and everything Sent from my iPhoneOn Aug 21, 2023, at 5:07 AM, BrightDersonS @.> wrote:﻿ File "./src/main/python/main.py", line 1188 stats: dict[str, Any] = dict() # type: ignore ^ SyntaxError: annotated name 'stats' can't be global This appears when trying to start the save editor with "python ./src/main/python/main.py" —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: @.>

Yep, Silly me, I downloaded 3.10 but forgot to uninstall 3,7. It works now
