### ISSUE TITLE
execution too complex

### ISSUE THREAD

**Issue by YokujinKaze** [AnthonyMichaelTDM/DRG-Save-Editor#37]
the way this tool needs to be executed is way too unnecessarily complex

please provide a compiled version, thank you

**Comment by AnthonyMichaelTDM** [comment]
Distributing the source code rather than bundled executables helps users be able to manually verify the integrity of the software and gives users the flexibility to customize it to their needs. I imagine that most people already have the Python interpreter installed anyway, so bundling it in the distribution just adds unnecessary bloat.Python is an interpreted language, so a truly compiled distribution of the script isn’t really doable. it would involve basically bundling the entire Python interpreter, all the scripts’ dependencies, and the script itself and would be platform dependent.On Oct 27, 2023, at 8:16 PM, YokujinKaze ***@***.***> wrote:﻿
the way this tool needs to be executed is way too unnecessarily complex
please provide a compiled version, thank you

**Comment by AnthonyMichaelTDM** [comment]
#67 should fix this, we'll see once v1.9.0 is released
