### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'fbs_runtime'

### ISSUE THREAD

**Issue by Carnrage13** [AnthonyMichaelTDM/DRG-Save-Editor#51]
when i followed the 3rd command i get error like this https://imgur.com/5DGCxgT

i followed instructions video from [NerdyJosh1](https://github.com/NerdyJosh1)

**Comment by bbeenn1** [comment]
were you following this https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/issues/19#issuecomment-1367993617

> For anyone reading this, check that you're running Python 3.10 (python --version). Then run pip install PySide2 fbs.

**Comment by Carnrage13** [comment]
yes. i use Python 3.10 from microsoft store

**Comment by bbeenn1** [comment]
try launching using 
`python3 ./src/main/python/main.py`

I have still not seen any work on this to get the weapon experience parsed, and suck at hex otherwise I would take a look myself at this point - so I would be careful making any changes to saves besides the job experience section and credits (most of the other resources should work too, but I can't predict what any of it will do when it outputs the data to the save)

**Comment by AnthonyMichaelTDM** [comment]
since #67, we no longer depend on fbs, marking as closed
