### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alefcs23** [AnthonyMichaelTDM/DRG-Save-Editor#53]
File "./src/main/python/main.py", line 1188
    stats: dict[str, Any] = dict() # type: ignore
    ^
SyntaxError: annotated name 'stats' can't be global

when trying to execute

**Comment by bbeenn1** [comment]
You may want to confirm the version of python that is running the script 
`python --version`

I know python 3.10.11 works for me
From what I can see, I was the last person to make any changes to main.py (to fix a condition that should never occur but threw a context error). See Issue #44 
It works on my Machine ¯\_(ツ)_/¯

Also, the editor doesn't work since the Weapon XP information was put into the Save file in November, and has a strong chance of corrupting saves until that is managed.
See Issues #42 #48 #49 #52

**Comment by AnthonyMichaelTDM** [comment]
can you check if this is still an issue in the latest release

**Comment by AnthonyMichaelTDM** [comment]
Marking as closed, reopen if it's still an issue
